# Generated by Django 4.1.5 on 2023-01-31 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_veiculos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registros',
        ),
    ]
